theme = "gruvbox_transparent"

[editor]
line-number = "relative"
rulers = [85, 115]
scrolloff = 8
true-color = true
bufferline = "always"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "┊"

[editor.search]
smart-case = true
wrap-around = false

[editor.statusline]
left = ["mode", "file-type", "file-name", "spinner"]
center = []
right = ["diagnostics", "file-encoding", "selections", "position"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
snippets = true
goto-reference-include-declaration = true
