theme = "custom_theme"

[editor]
line-number = "relative"
rulers = [100]
scrolloff = 8
true-color = true
bufferline = "always"
color-modes = true
cursorline = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 3

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "┊"

[editor.search]
smart-case = true
wrap-around = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control"
]
center = [
  "file-name",
  "file-modification-indicator", 
]
right = [
  "diagnostics",
  "spinner",
  "file-type",
  "position",
  "position-percentage",
  "spacer",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = false
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.file-picker]
hidden = false
git-ignore = true
ignore = true
max-depth = 5

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
esc = ["collapse_selection", "keep_primary_selection"]

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
