theme = "onedark"

[editor]
line-number = "relative"
rulers = [85, 115]
scrolloff = 5
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "┊"

[editor.search]
smart-case = true
wrap-around = false