theme = "custom_theme"

[editor]
line-number = "relative"
rulers = [95]
scrolloff = 8
true-color = true
bufferline = "always"
color-modes = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 3

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "┊"

[editor.search]
smart-case = true
wrap-around = false

[editor.statusline]
left = ["mode", "file-type", "file-name", "file-modification-indicator", "spinner"]
center = []
right = ["diagnostics", "file-encoding", "selections", "position"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
snippets = true
goto-reference-include-declaration = true

[editor.file-picker]
hidden = false
git-ignore = true
ignore = true
max-depth = 5
