[language-server.emmet-language-server]
args = ["--stdio"]
command = "emmet-language-server"

[language-server.tailwind-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.tailwind-ls.config]
tailwindCSS = { experimental = { classRegex = ["class=\"(.*)\""]}}

[language-server.rust-analyzer.config]
cargo = { buildScripts = { enable = true }, features = "all" }
check = { features = "all" }
procMacro = { enable = true }

#[language-server.rust-analyzer.config.inlayHints]
#lifetimeElisionHints = { enable = false, useParameterNames = false}

[[language]]
name = "html"
language-servers = ["tailwind-ls", "vscode-html-language-server", "emmet-language-server"]

[[language]]
name = "css"
language-servers = ["tailwind-ls", "vscode-css-language-server"]

